CREATE DATABASE equipe1;
use equipe1;

CREATE TABLE usuarios (
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(200) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARBINARY(128) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE paciente (
id INT NOT NULL,
nome VARCHAR(45) NOT NULL,
CPF INT NOT NULL,
altura FLOAT NOT NULL,
peso FLOAT NOT NULL,
data_nascimento DATE NOT NULL,
endereco VARCHAR(45) NOT NULL,
email VARCHAR(60) NOT NULL,
telefone VARCHAR(14) NOT NULL,
imagem_perfil VARCHAR(200) NOT NULL,
PRIMARY KEY (CPF)
);

CREATE TABLE consulta (
id INT NOT NULL,
data_consulta DATE NOT NULL,
hora TIME NOT NULL,
valor FLOAT NOT NULL,
descricao VARCHAR(100) NOT NULL,
CPF VARCHAR(14) NOT NULL,
CRMV INT NOT NULL,
PRIMARY KEY (CPF, CRMV),
FOREIGN KEY (CPF) REFERENCES paciente(CPF),
FOREIGN KEY (CRMV) REFERENCES doutor(CRMV)
);

CREATE TABLE doutor (
CRMV INT NOT NULL,
nome VARCHAR(45) NOT NULL,
area VARCHAR(45) NOT NULL,
imagem_perfil VARCHAR(200) NOT NULL,
PRIMARY KEY (CRMV)
);


