DROP DATABASE equipe1;
CREATE DATABASE equipe1;
use equipe1;

CREATE TABLE usuarios (
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(200) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARBINARY(128) NOT NULL,
imagem_perfil VARCHAR(200),
PRIMARY KEY (id)
);

CREATE TABLE pacientes (
id_user INT NOT NULL,
nome VARCHAR(45) NOT NULL,
CPF VARCHAR(14) NOT NULL,
altura FLOAT NOT NULL,
peso FLOAT NOT NULL,
data_nascimento DATE NOT NULL,
email VARCHAR(60) NOT NULL,
telefone VARCHAR(14) NOT NULL,
endereco VARCHAR(100) NOT NULL,
cidade VARCHAR(100) NOT NULL,
observacoes VARCHAR(200),
PRIMARY KEY (CPF)
);

CREATE TABLE medicos (
id_user INT NOT NULL,
CRM INT NOT NULL,
nome VARCHAR(45) NOT NULL,
telefone INT NOT NULL,
especializacao VARCHAR(45) NOT NULL,
PRIMARY KEY (CRM)
);

CREATE TABLE consultas (
id_user INT NOT NULL,
data_consulta DATE NOT NULL,
hora TIME NOT NULL,
valor FLOAT NOT NULL,
descricao VARCHAR(100) NOT NULL,
CPF VARCHAR(14) NOT NULL,
CRM INT NOT NULL,
PRIMARY KEY (CPF, CRM),
FOREIGN KEY (CPF) REFERENCES pacientes(CPF),
FOREIGN KEY (CRM) REFERENCES medicos(CRM)
);


